// <auto-generated />
using System;
using BloggingAppAuthenticationAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloggingAppAuthenticationAPI.Migrations
{
    [DbContext(typeof(BloggerDbContext))]
    [Migration("20191027140549_BloggerTableMigration")]
    partial class BloggerTableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BloggingAppAuthenticationAPI.Model.Blogger", b =>
                {
                    b.Property<int>("BloggerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BloggerDOB");

                    b.Property<string>("BloggerEmail")
                        .IsRequired();

                    b.Property<string>("BloggerFullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("BloggerPasswordHash")
                        .IsRequired();

                    b.Property<string>("BloggerSalt")
                        .IsRequired();

                    b.HasKey("BloggerId");

                    b.ToTable("Bloggers");
                });
#pragma warning restore 612, 618
        }
    }
}
